### ISSUE TITLE
Scan Roms in Sub Folders

### ISSUE THREAD

**Issue by rafaelvasco** [ButcheredGenre/ROMLauncher#1]
Allow scanning roms in subfolders:

Example: 
PSX Roms Folder: E:\Roms\PSX
PSX Rom Extension: cue

Folder Contents:
E:\Roms\PSX\Alundra\Alundra.cue
E:\Roms\PSX\Alundra\Alundra.bin

Current Final Rom List: 

(Empty)

Desired Final Rom List:

- Alundra

**Comment by ju-am** [comment]
Added optional recursive directory search in commit fff3c49. The changes will be included in version 1.2, though I want to push some additional changes before I update the binaries. Feel free to download & replace the /app/ directory manually if you want the changes earlier.

**Comment by rafaelvasco** [comment]
Thanks!
